version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: https://cashper.ai
    container_name: cashper_app
    restart: always
    ports:
      - "8080:8000"
    env_file:
      - ./cashper_backend/.env
    depends_on:
      - mongo
    volumes:
      - uploads_data:/app/uploads

  mongo:
    image: mongo:latest
    container_name: cashper_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  uploads_data: # Persistent storage for file uploads
